# Generated by Django 6.0.3 on 2026-03-26 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Открытость')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(verbose_name='Место по оси x')),
                ('y', models.IntegerField(verbose_name='Место по оси Y')),
                ('width', models.IntegerField(verbose_name='Длина')),
                ('height', models.IntegerField(verbose_name='Высота')),
                ('color', models.CharField(verbose_name='Цвет')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Block.room')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
    ]
