# Generated by Django 6.0.3 on 2026-03-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Block', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='room_id',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.BooleanField(default=1, verbose_name='Открытость'),
        ),
    ]
