# Generated by Django 6.0.3 on 2026-03-27 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Block', '0002_rename_room_id_block_room_alter_room_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Открытость'),
        ),
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='block',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks',
                                    to='Block.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('protected', 'Protected'), ('private', 'Private')],
                                   default='private', max_length=20),
        ),
        migrations.CreateModel(
            name='ShareRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares',
                                           to='Block.room')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              related_name='shared_rooms_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           related_name='shared_rooms_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к комнате',
                'verbose_name_plural': 'Доступы к комнатам',
            },
        ),
    ]
