# Generated by Django 6.0.3 on 2026-03-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Block', '0003_room_open_room_user_alter_block_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('rectangle', 'Rectangle'), ('triangle', 'Triangle'), ('circle', 'Circle'), ('text', 'Text')], default='rectangle'),
        ),
    ]
